name: Build SquatPotato

on:
  push:
    tags: [ "v*" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: csc
        shell: cmd
        run: >
          "%WINDIR%\Microsoft.NET\Framework64\v4.0.30319\csc.exe"
          /nologo /target:exe /platform:x64 /unsafe
          /out:SquatPotato.exe SquatPotato.cs

      - name: Release
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.ref_name }} SquatPotato.exe `
            --title ${{ github.ref_name }}
